# Generated by Django 3.1.3 on 2020-12-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('ssn', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiptDate', models.DateField(verbose_name='receipt date')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending.user')),
            ],
        ),
    ]
